name: quirknthreads
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auth_client:
    path: packages/auth_client
  db_client:
    path: packages/db_client
  payment_client:
    path: packages/payment_client
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  uuid: ^4.2.2
  flutter_stripe: ^10.0.0
  firebase_auth: ^4.19.2
  flutter_bloc: ^8.1.5
  go_router: ^13.2.4
  intl: ^0.17.0
  openid_client: ^0.4.8
  url_launcher: ^6.2.6
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.2.2+5


dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^2.0.0


flutter:




  uses-material-design: true































